### ISSUE TITLE
no_shortcuts  does not work with quadratic bezier curves

### ISSUE THREAD

**Issue by benkasminbullock** [benkasminbullock/Image-SVG-Path#19]
The no_shortcuts option to extract_path_info does not work with quadratic bezier curves.

**Comment by kekoa** [comment]
Turns out not only is no_shortcuts broken for quadratic beziers, but also absolute is broken too.  The code just isn't there.  I needed it and wrote it, so here's a patch.  Not sure if you'll do anything with it but at least it'll be here for whoever wants it.

I also fixed an issue where the implementation gives up on smooth curves if the previous curve was not a curve of the same type.  This [page](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d) says to repeat the first control point, which was easy to implement.

[Image-SVG-Path-0.32.patch.txt](https://github.com/benkasminbullock/Image-SVG-Path/files/4833154/Image-SVG-Path-0.32.patch.txt)

**Comment by benkasminbullock** [comment]
Thank you for the patch.

Do you have a simple example of these forms of curve which I could use in a
test?

**Comment by kekoa** [comment]
What works as a test for you?  I was pulling these out of an svg font and putting separate glyphs into separate svg files.  I was satisfied when absolute/smoothed paths rendered the same as the source font.  Because the svg I used came from a font, I don't have anything clearly simple, but they're not too complicated either.  It would be easy enough to find you an example or two that exercise the various code paths, then send you before/after strings.  Does that work for you?

As an example (this might not be one that tests all the cases) we're talking about strings that aren't very long, like:

M171 31q-3 -12 -29 -15.5t-32 32.5q-23 113 -33 291t-13.5 376.5t-3 396t0.5 349.5q11 139 180 28q195 -131 343.5 -315.5t288.5 -383.5q15 -24 7 -35.5t-26 2.5q-171 120 -318 250t-288 260q0 -75 -4.5 -162t-4.5 -160q169 -139 290.5 -262t255.5 -288q13 -17 14.5 -32.5t-34.5 1.5q-52 22 -227.5 139t-301.5 212q-12 -360 -65 -684z

**Comment by benkasminbullock** [comment]
If you know how to write a test for a Perl module then it would be easiest
for me if you just wrote a test file. If you don't know how to do that then
just give me some inputs and the outputs that you expect to get which you
weren't getting before you patched the module.

Thanks.

**Comment by kekoa** [comment]
I'll update Image-SVG-Path.t and send an updated patch in a day or two.

**Comment by kekoa** [comment]
Ended up with some free time and hand-crafted a few tests.  Updated patch attached.

[Image-SVG-Path-0.32.patch.txt](https://github.com/benkasminbullock/Image-SVG-Path/files/4839284/Image-SVG-Path-0.32.patch.txt)

**Comment by benkasminbullock** [comment]
Thank you, I have added everything and this is now on CPAN as version 0.33.

https://metacpan.org/release/BKB/Image-SVG-Path-0.33

Let me know if there is anything else or if this is not resolved properly.
